// Run with SPOTTED_PGLITE_MODULE=/tmp/spotted-notification-tests/node_modules/@electric-sql/pglite node tests/notifications/database.cjs
const {PGlite}=require(process.env.SPOTTED_PGLITE_MODULE || '@electric-sql/pglite');
const fs=require('node:fs');
const path=require('node:path');
const assert=require('node:assert/strict');
(async()=>{
 const db=new PGlite();
 await db.exec(fs.readFileSync(path.join(__dirname,'bootstrap.sql'),'utf8'));
 const migration=fs.readFileSync(path.join(__dirname,'../../supabase/migrations/20260922205151_reliable_notification_delivery.sql'),'utf8');
 await db.exec(migration);
 const q=async sql=>(await db.query(sql)).rows;
 const scalar=async sql=>Object.values((await q(sql))[0])[0];
 let checks=0;
 const check=async(name,sql,expected)=>{assert.deepEqual(await scalar(sql),expected,name);checks++;console.log('PASS',name)};
 const a='11111111-1111-4111-8111-111111111111',b='22222222-2222-4222-8222-222222222222',c='33333333-3333-4333-8333-333333333333',d='44444444-4444-4444-8444-444444444444',post='55555555-5555-4555-8555-555555555555',thread='66666666-6666-4666-8666-666666666666';
 await db.exec(`insert into profiles(id,display_name) values('${a}','Alice'),('${b}','Bob'),('${c}','Carol'),('${d}','Dora');
 insert into friendships(user_id,friend_id,status) values('${a}','${b}','pending');
 update friendships set status='accepted';
 insert into friendships(user_id,friend_id,status) values('${b}','${c}','accepted');
 insert into posts(id,user_id) values('${post}','${a}');`);
 await check('accepted request produces one alert',`select count(*)::int from notifications where type='friend_accepted'`,1);
 await check('accepted request queues one push',`select count(*)::int from push_outbox`,1);
 await db.exec(`select set_config('request.jwt.claim.sub','${b}',false);select * from create_notification('${a}','friend_accepted','legacy duplicate');`);
 await check('old client cannot duplicate accepted alert',`select count(*)::int from notifications where type='friend_accepted'`,1);
 await db.exec(`insert into post_likes(post_id,user_id) values('${post}','${b}');select * from create_notification('${a}','post_like','old client duplicate');`);
 await check('like trigger plus old client yields one alert',`select count(*)::int from notifications where type='post_like'`,1);
 await db.exec(`insert into post_likes(post_id,user_id) values('${post}','${b}');`);
 await check('unlike/re-like does not spam',`select count(*)::int from notifications where type='post_like'`,1);
 await db.exec(`insert into post_comments(post_id,user_id,text) values('${post}','${b}','hello');`);
 await check('comment queues push',`select count(*)::int from notifications n join push_outbox q on q.notification_id=n.id where n.type='post_comment'`,1);
 await db.exec(`insert into post_comments(post_id,user_id,text) values('${post}','${a}','own');`);
 await check('self comment does not notify',`select count(*)::int from notifications where type='post_comment'`,1);
 await db.exec(`update posts set visibility='close_friends';insert into post_tags(post_id,tagged_user_id) values('${post}','${b}');`);
 await check('outside-audience tag creates no alert',`select count(*)::int from notifications where type='post_tag'`,0);
 await db.exec(`insert into close_friends values('${a}','${b}');insert into post_tags(post_id,tagged_user_id) values('${post}','${b}');`);
 await check('visible tag queues one push',`select count(*)::int from notifications n join push_outbox q on q.notification_id=n.id where n.type='post_tag'`,1);
 await check('tag omits venue content',`select message like '%at %' from notifications where type='post_tag'`,false);
 await db.exec(`delete from close_friends;`);
 await check('privacy tightening prevents queued tag delivery',`select push_notification_allowed(id) from notifications where type='post_tag'`,false);
 await db.exec(`update profiles set location_sharing_level='mutual_friends' where id='${a}';select set_config('request.jwt.claim.sub','${a}',false);`);
 await check('planning includes direct friend and friend-of-friend',`select get_planning_notification_recipients() @> array['${b}','${c}']::uuid[]`,true);
 await check('planning excludes stranger',`select '${d}'::uuid=any(get_planning_notification_recipients())`,false);
 await db.exec(`insert into location_hidden values('${a}','${c}');`);
 await check('planning respects hidden recipients',`select '${c}'::uuid=any(get_planning_notification_recipients())`,false);
 await db.exec(`insert into dm_thread_members values('${thread}','${a}'),('${thread}','${b}');insert into dm_messages(thread_id,sender_id,text) values('${thread}','${a}','hi');`);
 await check('DM preserves message preview',`select message from notifications where type='dm'`,'Alice: hi');
 await check('DM carries exact thread destination',`select data->>'thread_id' from notifications where type='dm'`,thread);
 await db.exec(`select * from create_notification('${b}','dm','legacy duplicate');`);
 await check('legacy DM does not double-send',`select count(*)::int from notifications where type='dm'`,1);
 await db.exec(`insert into blocked_users values('${b}','${a}');insert into dm_messages(thread_id,sender_id,text) values('${thread}','${a}','blocked');`);
 await check('blocked sender creates no DM alert',`select count(*)::int from notifications where type='dm'`,1);
 await check('new block cancels an existing queued DM',`select push_notification_allowed(id) from notifications where type='dm'`,false);
 await check('queue disabled by default',`select count(*)::int from claim_push_batch()`,0);
 await db.exec(`update spotted_private.push_settings set delivery_enabled=true;`);
 const jobs=await q('select * from claim_push_batch()');assert(jobs.length>0);checks++;
 await check('concurrent claim cannot take leased jobs',`select count(*)::int from claim_push_batch()`,0);
 const job=jobs[0];
 await db.exec(`select finish_push('${job.notification_id}','${d}','sent',null,'{}');`);
 await check('wrong lease cannot acknowledge delivery',`select state from push_outbox where notification_id='${job.notification_id}'`,'sending');
 await db.exec(`select finish_push('${job.notification_id}','${job.lease_id}','pending','temporary failure','{}');`);
 await check('temporary failure stays retryable',`select state from push_outbox where notification_id='${job.notification_id}'`,'pending');
 await check('retry uses future backoff',`select available_at>now() from push_outbox where notification_id='${job.notification_id}'`,true);
 await db.exec(`update push_outbox set available_at=now()-interval '1 second',attempts=4 where notification_id='${job.notification_id}';`);
 const last=(await q('select * from claim_push_batch()'))[0];
 await db.exec(`select finish_push('${last.notification_id}','${last.lease_id}','pending','failure','{}');`);
 await check('retry cap creates visible failed state',`select state from push_outbox where notification_id='${last.notification_id}'`,'failed');
 await db.exec(`update push_outbox set lease_until=now()-interval '1 minute',expires_at=now()-interval '1 minute' where state='sending';select * from claim_push_batch();`);
 await check('expired alerts are never claimed',`select count(*)::int from push_outbox where state='sending'`,0);
 await check('clients cannot read queue',`select has_table_privilege('authenticated','public.push_outbox','SELECT')`,false);
 await check('clients cannot claim queue',`select has_function_privilege('authenticated','public.claim_push_batch()','EXECUTE')`,false);
 await check('clients cannot call internal audience helper',`select has_function_privilege('authenticated','spotted_private.audience_allows(uuid,uuid,text)','EXECUTE')`,false);
 await check('campaigns disabled by default',`select enqueue_scheduled_pushes()`,0);
 await db.exec(`delete from notifications where id='${last.notification_id}';`);
 await check('deleting alert cancels queued work',`select count(*)::int from push_outbox where notification_id='${last.notification_id}'`,0);


 await db.exec(`delete from blocked_users;delete from night_statuses;
 insert into night_statuses(user_id,venue_id,status,expires_at) values('${a}','${post}','out',now()+interval '2 hours');
 select set_config('request.jwt.claim.sub','${a}',false);
 select * from create_notification('${b}','friend_arrived_venue','Alice arrived at Bar A');`);
 await check('arrival captures current venue',`select data->>'venue_id' from notifications where type='friend_arrived_venue'`,post);
 await check('current arrival is eligible',`select push_notification_allowed(id) from notifications where type='friend_arrived_venue'`,true);
 await db.exec(`update night_statuses set venue_id='${thread}' where user_id='${a}';`);
 await check('moving to next bar cancels delayed old-bar alert',`select push_notification_allowed(id) from notifications where type='friend_arrived_venue'`,false);
 await db.exec('delete from night_statuses');
 // Freeze only the scheduler's clock inside this isolated database. The
 // production function always uses database now(); no clock override is exposed.
 const scheduler=(await q("select pg_get_functiondef('public.enqueue_scheduled_pushes()'::regprocedure) as definition"))[0].definition;
 const clock=async iso=>db.exec(scheduler.replaceAll('now()',`'${iso}'::timestamptz`));
 await db.exec(`update spotted_private.push_settings set campaigns_enabled=true;
 update profiles set apns_device_token=repeat('a',64);
 update profiles set city='la' where id='${c}';update profiles set is_demo=true where id='${d}';
 insert into night_statuses(user_id,status,expires_at) values('${b}','home','2026-09-24T09:00:00Z');`);
 await clock('2026-09-23T22:00:00Z');
 await check('NY 6pm sends only to unanswered eligible NY users',`select enqueue_scheduled_pushes()`,1);
 await check('LA does not receive NY-time campaign',`select count(*)::int from notifications where type='daily_nudge_first' and receiver_id='${c}'`,0);
 await check('answered No suppresses campaign',`select count(*)::int from notifications where type='daily_nudge_first' and receiver_id='${b}'`,0);
 await check('repeated scheduler run is idempotent',`select enqueue_scheduled_pushes()`,0);
 await clock('2026-09-24T00:00:00Z');
 await check('follow-up waits for actual first-send success',`select enqueue_scheduled_pushes()`,0);
 await db.exec(`update push_outbox set state='sent' where notification_id in(select id from notifications where type='daily_nudge_first');`);
 await check('delivered first reminder allows one follow-up',`select enqueue_scheduled_pushes()`,1);
 await db.exec(`delete from notifications where type='daily_nudge_second';insert into night_statuses(user_id,status,expires_at) values('${a}','home','2026-09-24T09:00:00Z');`);
 await check('No after first reminder suppresses second',`select enqueue_scheduled_pushes()`,0);
 await db.exec('delete from night_statuses');await clock('2026-09-25T21:00:00Z');
 await check('Friday rally is scheduled at city-local 5pm',`select enqueue_scheduled_pushes()`,2);
 await clock('2026-09-25T22:00:00Z');
 await check('Friday rally replaces 6pm nudge',`select enqueue_scheduled_pushes()`,0);
 await clock('2026-09-24T01:00:00Z');
 await check('LA gets its own 6pm reminder',`select enqueue_scheduled_pushes()`,1);
 console.log(`${checks} database checks passed`);await db.close();
})().catch(e=>{console.error(e);process.exitCode=1});
