-- Update NYC venues with granular neighborhood data
UPDATE venues SET neighborhood = 'Meatpacking' WHERE name = 'Le Bain' AND city = 'nyc';
UPDATE venues SET neighborhood = 'Bushwick' WHERE name = 'House of Yes' AND city = 'nyc';
UPDATE venues SET neighborhood = 'Lower East Side' WHERE name = 'The Box' AND city = 'nyc';
UPDATE venues SET neighborhood = 'Bushwick' WHERE name = 'Elsewhere' AND city = 'nyc';
UPDATE venues SET neighborhood = 'Williamsburg' WHERE name = 'TBA Brooklyn' AND city = 'nyc';
UPDATE venues SET neighborhood = 'Ridgewood' WHERE name = 'Nowadays' AND city = 'nyc';
UPDATE venues SET neighborhood = 'Lower East Side' WHERE name = 'Double Chicken Please' AND city = 'nyc';
UPDATE venues SET neighborhood = 'Financial District' WHERE name = 'The Dead Rabbit' AND city = 'nyc';
UPDATE venues SET neighborhood = 'West Village' WHERE name = 'Dante NYC' AND city = 'nyc';
UPDATE venues SET neighborhood = 'Lower East Side' WHERE name = 'Attaboy' AND city = 'nyc';
UPDATE venues SET neighborhood = 'Chelsea' WHERE name = 'PHD Rooftop' AND city = 'nyc';
UPDATE venues SET neighborhood = 'Flatiron' WHERE name = '230 Fifth' AND city = 'nyc';
UPDATE venues SET neighborhood = 'Williamsburg' WHERE name = 'Schimanski' AND city = 'nyc';
UPDATE venues SET neighborhood = 'Greenpoint' WHERE name = 'Good Room' AND city = 'nyc';
UPDATE venues SET neighborhood = 'East Village' WHERE name = 'Superbueno' AND city = 'nyc';
UPDATE venues SET neighborhood = 'Carroll Gardens' WHERE name = 'Sunken Harbor Club' AND city = 'nyc';
UPDATE venues SET neighborhood = 'East Village' WHERE name = 'schmuck.' AND city = 'nyc';
UPDATE venues SET neighborhood = 'Lower East Side' WHERE name = 'Public Hotel Rooftop' AND city = 'nyc';
UPDATE venues SET neighborhood = 'SoHo' WHERE name = 'Jean''s' AND city = 'nyc';
UPDATE venues SET neighborhood = 'Midtown' WHERE name = 'The Campbell' AND city = 'nyc';
UPDATE venues SET neighborhood = 'East Village' WHERE name = 'Bar Snack' AND city = 'nyc';
UPDATE venues SET neighborhood = 'SoHo' WHERE name = 'Saint Tuesday' AND city = 'nyc';
UPDATE venues SET neighborhood = 'SoHo' WHERE name = 'Sunn''s' AND city = 'nyc';
UPDATE venues SET neighborhood = 'SoHo' WHERE name = 'The Mulberry' AND city = 'nyc';
UPDATE venues SET neighborhood = 'Lower East Side' WHERE name = 'Amber Room' AND city = 'nyc';
UPDATE venues SET neighborhood = 'Lower East Side' WHERE name = 'Patent Pending' AND city = 'nyc';
UPDATE venues SET neighborhood = 'SoHo' WHERE name = 'Ketchy Shuby' AND city = 'nyc';
UPDATE venues SET neighborhood = 'SoHo' WHERE name = 'Gospël' AND city = 'nyc';
UPDATE venues SET neighborhood = 'SoHo' WHERE name = 'Paul''s Casablanca' AND city = 'nyc';
UPDATE venues SET neighborhood = 'West Village' WHERE name = 'Paul''s Cocktail Lounge' AND city = 'nyc';
UPDATE venues SET neighborhood = 'East Village' WHERE name = 'The Nines' AND city = 'nyc';
UPDATE venues SET neighborhood = 'East Village' WHERE name = 'Little Sister Lounge' AND city = 'nyc';
UPDATE venues SET neighborhood = 'Williamsburg' WHERE name = 'Unveiled' AND city = 'nyc';
UPDATE venues SET neighborhood = 'Bushwick' WHERE name = 'Studio Maison Nur' AND city = 'nyc';